# Generated by Django 4.2.9 on 2024-06-12 05:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chapter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="updated_at",
        ),
    ]
