# Generated by Django 4.2.9 on 2024-06-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': '章節', 'verbose_name_plural': '章節們'},
        ),
    ]
