# Generated by Django 4.2.9 on 2024-06-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0002_alter_chapter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='assistant_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
