# Generated by Django 4.2.9 on 2024-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=255, unique=True, verbose_name="手機號碼"),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, null=True, verbose_name="電子郵件"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=254, null=True, verbose_name="使用者名稱"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "tml_house_id",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="家庭編號"
                    ),
                ),
                (
                    "tml_person_id",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="個人編號"
                    ),
                ),
                (
                    "line_id",
                    models.CharField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Line ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
