# Generated by Django 4.2.9 on 2024-06-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_siteuser_phone_alter_siteuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='line_id',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='tml_house_id',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='tml_person_id',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='手機'),
        ),
    ]
