# Generated by Django 4.2.9 on 2024-04-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20240416_0039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
