# Generated by Django 4.2.9 on 2024-05-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20240428_1221"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteuser",
            name="line_id",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="siteuser",
            name="email",
            field=models.EmailField(
                max_length=255, null=True, verbose_name="電子郵件地址"
            ),
        ),
        migrations.AlterField(
            model_name="siteuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
