# Generated by Django 4.2.9 on 2024-05-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_siteuser_line_id_alter_siteuser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteuser",
            name="line_id",
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
