# Generated by Django 4.2.9 on 2024-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_siteuser_line_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteuser",
            name="email",
            field=models.EmailField(max_length=255, null=True, verbose_name="電子郵件"),
        ),
        migrations.AlterField(
            model_name="siteuser",
            name="line_id",
            field=models.CharField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Line ID",
            ),
        ),
        migrations.AlterField(
            model_name="siteuser",
            name="phone",
            field=models.CharField(
                max_length=255,
                unique=True,
                verbose_name="手機號碼",
            ),
        ),
        migrations.AlterField(
            model_name="siteuser",
            name="tml_house_id",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="家庭編號",
            ),
        ),
        migrations.AlterField(
            model_name="siteuser",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="使用者名稱",
            ),
        ),
    ]
