# Generated by Django 4.2.9 on 2024-05-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_siteuser_email_alter_siteuser_line_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteuser",
            name="tml_person_id",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="個人編號",
            ),
        ),
    ]
