# Generated by Django 4.2.9 on 2024-06-13 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='線程 ID'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='訊息內容'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='標籤'),
        ),
    ]
