# Generated by Django 4.2.9 on 2024-06-13 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10, verbose_name='角色')),
                ('content', models.TextField(verbose_name='訊息內容')),
                ('tag', models.CharField(max_length=20, verbose_name='標籤')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='訊息時間戳')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatbot', verbose_name='聊天機器人')),
            ],
            options={
                'verbose_name': '聊天訊息',
                'verbose_name_plural': '聊天訊息們',
            },
        ),
    ]
