# Generated by Django 4.2.9 on 2024-06-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_created_at_chatmessage_thread_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='assistant_ids',
            field=models.JSONField(default=list, verbose_name='助理ID'),
        ),
    ]
