# Generated by Django 4.2.9 on 2024-06-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_created_at_chatmessage_thread_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Python程式碼'),
        ),
    ]
