# Generated by Django 4.2.9 on 2024-06-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatbot_assistant_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='assistant_ids',
        ),
    ]
