# Generated by Django 4.2.9 on 2024-06-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatbot_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='message_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='上傳檔案 ID'),
        ),
    ]
