# Generated by Django 4.2.9 on 2024-06-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatbot_message_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='message_file_id',
            new_name='message_file',
        ),
    ]
