from django.urls import path, re_path

from apps.management_sample import views


html_files = [
    "account-setting.html",
    "add-user.html",
    "calendar.html",
    "chat.html",
    "dashboard1.html",
    "data-table.html",
    "form-chechbox.html",
    "form-layout.html",
    "form-radio.html",
    "form-switch.html",
    "form-validation.html",
    "icon-dripicons.html",
    "icon-fontawesome-5.html",
    "icon-lineawesome.html",
    "icon-remixicon.html",
    "icon-unicons.html",
    "index.html",
    "pages-confirm-mail.html",
    "pages-lock-screen.html",
    "pages-recoverpw.html",
    "privacy-policy.html",
    "privacy-setting.html",
    "profile-edit.html",
    "profile.html",
    "sign-in.html",
    "sign-up.html",
    "table-editable.html",
    "tables-basic.html",
    "terms-of-service.html",
    "todo.html",
    "ui-alerts.html",
    "ui-badges.html",
    "ui-breadcrumb.html",
    "ui-buttons.html",
    "ui-cards.html",
    "ui-carousel.html",
    "ui-colors.html",
    "ui-dropdowns.html",
    "ui-embed-video.html",
    "ui-grid.html",
    "ui-images.html",
    "ui-list-group.html",
    "ui-media-object.html",
    "ui-modal.html",
    "ui-notifications.html",
    "ui-pagination.html",
    "ui-popovers.html",
    "ui-progressbars.html",
    "ui-tabs.html",
    "ui-tooltips.html",
    "ui-typography.html",
    "user-list.html",
    "email-compose.html",
    "email-index.html",
]

html_files_pattern = "|".join(html_files)  # 将文件名列表转换为正则表达式的模式
urlpatterns = [
    path("", views.index, name="management_sample"),  # Default index view
    re_path(rf"^(?P<filename>({html_files_pattern}))$", views.generate_view),
    # path("register_users", views.register_users, name="management_sample=register_users"),
    # path("login_userss", views.login_users, name="management_sample-login_userss"),
    # path("show_users", views.show_users, name="management_sample-show_users"),
    # path("logout_user", views.logout_user, name="management_sample-logout_user"),
    # path('<str:filename>', views.generate_view),
]
